name: 报告问题 / Bug report
description: 提交一份问题报告帮助开发者改进模块 / Submit a bug report to help developers improve the module
title: "[BUG] "
labels: [ "Bug" ]

body:
  - type: markdown
    attributes:
      value: |
        感谢给 WeKit 汇报问题！
        为了使我们更好地帮助你，请完整、准确地提供以下信息。
        
        Thank you for reporting an issue to WeKit!
        To help us assist you better, please provide the following information completely and accurately.
  - type: textarea
    attributes:
      label: 复现步骤 / Steps to reproduce
      placeholder: |
        1. 打开应用的某个页面
        2. 点击特定按钮
        3. 观察到错误发生
        
        1. Open a specific page in the app
        2. Click a particular button
        3. Observe the error occurring
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期行为 / Expected behaviour
      placeholder: 正常情况下应该发生什么 / Describe what should happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实际行为 / Actual behaviour
      description: 如果含有截图，个人信息注意打码保护 / If attaching screenshots, blur or mask any personal information for privacy protection
      placeholder: 实际上发生了什么 / Describe what actually happens instead
    validations:
      required: true
  - type: input
    attributes:
      label: 你使用的 Xposed 框架 / Xposed Framework you used
      placeholder: LSPosed 1.9.2-it
    validations:
      required: true
  - type: input
    attributes:
      label: 你使用的安卓系统版本 / Your Android version
      placeholder: Android 13
    validations:
      required: true
  - type: input
    attributes:
      label: 微信版本 / WeChat Version
      placeholder: 8.0.67
    validations:
      required: true
  - type: input
    attributes:
      label: 模块版本 / Module Version
      description: 不要使用“最新版”。给出详细版本号，否则 issue 将被关闭。在 https://t.me/wekit_ci 获取最新 CI 版本。 / Do not use "latest". Specify the exact version number, otherwise your issue will be closed. Get the latest CI version from https://t.me/wekit_ci.
    validations:
      required: true
  - type: checkboxes
    id: latest
    attributes:
      label: 版本和其他要求 / Version and Other Requirements
      options:
        - label: 我正在使用最新 CI 版本且启用日志记录 / I am using the latest CI version of WeKit and have enabled logging
        - label: 我使用的微信是官方发布的正式版本，而非修改版或测试版 / The WeChat I am using is an official release version, not a modified or beta version
        - label: 我已经在 [Issue Tracker](https://github.com/cwuom/wekit/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。 / I have searched the [Issue Tracker](https://github.com/cwuom/wekit/issues) and confirmed no duplicate issues exist. Duplicate issues will be closed.
          required: true
        - label: 我已知晓并同意，此处仅用于汇报本模块中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。 / I understand and agree that this section is only for reporting issues with the main program. If this issue is about other non-program-related problems, it may be closed and/or locked unconditionally.
          required: true
        - label: 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。 / I understand and agree that my issue may be deleted unconditionally if I do not follow the instructions in this template.
          required: true
  - type: textarea
    attributes:
      label: 日志 / Logs
      description: 因错误追踪系统不完善，此项非必填。如果条件允许，可使用 LogFox 抓取运行日志，或是上传 `/storage/emulated/0/Android/data/com.tencent.mm/WeKit/log/ErrorLog/` 内的日志。 / This field is optional due to the incomplete error tracking system. If possible, capture runtime logs with LogFox, or upload log files from `/storage/emulated/0/Android/data/com.tencent.mm/WeKit/log/ErrorLog/`.
      placeholder: 将日志粘贴到此处或者点击文本框底栏上传日志文件。 / Paste logs here or upload log files by clicking the attachment bar at the bottom of the text box.
    validations:
      required: false
  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选） / Additional information (optional)
      placeholder: 其他与该问题相关的信息 / Any other relevant information about the issue
    validations:
      required: false