// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1769058834977

#pragma once
#include <vector>
#include <cstdint>

static const int EXPECTED_DEX_COUNT = 3;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0x2075AFC3, 0x31D9502B, 0x18F4C7CE };